# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Math-Round-0.06

DESCRIPTION="extension for rounding numbers"
HOMEPAGE="http://search.cpan.org/search?query=Math-Round&mode=dist"
SRC_URI="mirror://cpan/authors/id/G/GR/GROMMEL/${P}.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64 x86"

