# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="extension for manipulating IPv4 addresses"
HOMEPAGE="http://search.cpan.org/search?query=Net-IPv4Addr&mode=dist"
SRC_URI="mirror://cpan/authors/id/F/FR/FRAJULAC/${P}.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64 x86"

