# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="extension for base 85 numbers, as referenced by RFC1924"
HOMEPAGE="http://search.cpan.org/search?query=Math-Base85&mode=dist"
SRC_URI="mirror://cpan/authors/id/T/TM/TMONROE/${P}.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64 x86"

