# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="class and object builder"
HOMEPAGE="http://search.cpan.org/search?query=Class-Gomor&mode=dist"
SRC_URI="mirror://cpan/authors/id/G/GO/GOMOR/${P}.tar.gz"

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64 x86"
RESTRICT="primaryuri"
IUSE=""

DEPEND="dev-lang/perl"
